### ISSUE TITLE
Kernel build(undefined symbol: __stack_chk_guard). Anyone help?

### ISSUE THREAD

**Issue by uame426** [tangalbert919/android_device_oneplus_sm8450-common#2]
OS: ubuntu 18.04

mkdir -p out
export ARCH=arm64
export SUBARCH=arm64
export DTC_EXT=~/Desktop/onePlus10Pro/toolchains/dtc/dtc
export CLANG_PATH=~/Desktop/onePlus10Pro/toolchains/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/
export PATH=${CLANG_PATH}:${PATH}
export LLVM=1
export CLANG_TRIPLE=aarch64-linux-gnu-
export CROSS_COMPILE=~/Desktop/onePlus10Pro/toolchains/aarch64-linux-android-4.9/bin/aarch64-linux-android-
export CROSS_COMPILE_ARM32=~/Desktop/onePlus10Pro/toolchains/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
export LD_LIBRARY_PATH=~/Desktop/onePlus10Pro/toolchains/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04/lib:$LD_LIBRARY_PATH
make  CC=clang  O=out config_oneplus_sm8450_defconfig
make -j$(nproc) CC=clang   O=out

The ld  error result: 
...
  CHK     include/generated/autoksyms.h
  GEN     .version
  CHK     include/generated/compile.h
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
ld.lld: error: undefined symbol: __stack_chk_guard
>>> referenced by initcall.h:10 (/home/msg/Desktop/onePlus10Pro/Third/android_kernel_oneplus_sm8450/out/../include/trace/events/initcall.h:10)
>>>               main.o:(trace_event_raw_event_initcall_level) in archive init/built-in.a
>>> referenced by initcall.h:10 (/home/msg/Desktop/onePlus10Pro/Third/android_kernel_oneplus_sm8450/out/../include/trace/events/initcall.h:10)
>>>               main.o:(trace_event_raw_event_initcall_level) in archive init/built-in.a
>>> referenced by initcall.h:10 (/home/msg/Desktop/onePlus10Pro/Third/android_kernel_oneplus_sm8450/out/../include/trace/events/initcall.h:10)
>>>               main.o:(trace_event_raw_event_initcall_level) in archive init/built-in.a
>>> referenced 41657 more times

**Comment by ziasam** [comment]
How did you fix this error?
